# Generated by Django 5.2.8 on 2025-11-12 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_address_address_name_en_address_address_name_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stores',
            old_name='store',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='address',
            name='store_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_addresses', to='mysite.stores'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='store_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_contacts', to='mysite.stores'),
        ),
        migrations.AlterField(
            model_name='menusstore',
            name='stores_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores_menus', to='mysite.stores'),
        ),
        migrations.AlterField(
            model_name='review',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_reviews', to='mysite.stores'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_stores', to='mysite.category'),
        ),
    ]
